log_base_dir: ./Run/logs/TAPNet
to_log_file: True
to_stdout: True
TB_dir: False
checkpoints: ./Run/checkpoints/TAPNet
log_level: INFO
model_name: dynamic_patching_model
# exp_name: regular

data:
  batch_size: 512
  split_dataset: [0.6, 0.2, 0.2] # 训练集、验证集、测试集的比例
  # interval: '3h'
  freq: '3600s' # '?s'
  data_name: regular
  root_path: dataset    # 数据集的目录
  data_path: ETTh1.csv # 60_LAV.csv  # 数据集的文件名
  num_workers: 3
  embed: 0
  target_num: 7
  collate_fn: collate_fn
  missing_rate: 0.0

model:
  apn_te_dim: 16 
  apn_npatch: 8 
  time_embed_type: rope
  var_att_type: mask_cross_att
  group_type: gap
  time: 1
  catt: 1
  gap: 1
  sweep: 0
  seq_len: 512
  pred_len: 96
  main_dim: 7
  d_ff: 128
  d_model: 64
  patch_len: 12
  seq_len_max_irr: null
  pred_len_max_irr: null
  patch_len_max_irr: null
  min_patch_size: 4
  use_fft: False
  fft_k: 2
  threshold: 0.5
  layer_number: 3
  enc_in: 7
  revin: 1
  e_layers: 3
  factor: 3
  n_heads: 2
  dropout: 0.1
  activation: gelu
  output_attention: False
  similarity_func: cosine
  gpu: 0
  dim:
    latent: 512
  odefunc:
    use: False
    ode_method: 'dopri5'
    odeint_atol: 1e-4
    odeint_rtol: 1e-3
    adjoint: False
  loss:
    pred_loss: True
    recon_loss: False
    recon_loss_weight: 1
    criterion: mse # mae

train:
  lr: 0.005
  lradj: 'TST'
  epochs: 300
  pct_start: 0.4
  patience: 10
  log_every: 1

GPU:
  use_gpu: True
  gpu: 0
  use_multi_gpu: False
  devices: '0, 1, 2, 3'