log_base_dir: ./Run/logs/TiWeaver
to_log_file: True
to_stdout: True
TB_dir: False
checkpoints: ./Run/checkpoints/TiWeaver
log_level: INFO
model_name: TiWeaver

data:
  batch_size: 512
  split_dataset: [0.7, 0.1, 0.2]
  data_name: exchange 
  root_path: dataset
  data_path: exchange.csv
  num_workers: 3
  embed: 0
  collate_fn: collate_fn
  missing_rate: 0.0

model:
  num_latent_token: 4
  sweep: 0
  seq_len: 596
  pred_len: 96
  main_dim: 7
  d_ff: 128
  d_model: 64
  patch_len: 12
  seq_len_max_irr: null
  pred_len_max_irr: null
  patch_len_max_irr: null
  min_patch_size: 4
  threshold: 0.5
  layer_number: 3
  enc_in: 7
  e_layers: 3
  factor: 3
  n_heads: 2
  dropout: 0.1
  activation: gelu
  output_attention: False
  similarity_func: cosine
  gpu: 0
  dim:
    latent: 512
  loss:
    criterion: mse 

train:
  lr: 0.005
  lradj: 'ExponentialDecayLR'
  epochs: 300
  pct_start: 0.4
  patience: 10
  log_every: 1

GPU:
  use_gpu: True
  gpu: 0
  use_multi_gpu: False
  devices: '0, 1, 2, 3'