log_base_dir: ./Run/logs/Lightgts_token
to_log_file: True
to_stdout: True
TB_dir: False
checkpoints: ./Run/checkpoints/Lightgts_token
log_level: INFO
model_name: Lightgts_token

data:
  batch_size: 1024
  split_dataset: [0.525, 0.175, 0.3] # 训练集、验证集、测试集的比例
  # interval: '3h'
  freq: '60s' # 'h'、'min'、's'
  data_name: BAOWU
  root_path: dataset    # 宝武数据集的目录
  data_path: merged_regular.csv # 60_LAV.csv  # 宝武数据集的文件名
  num_workers: 3
  embed: 0
  target_num: 1

model:
  seq_len: 336
  pred_len: 336
  main_dim: 1
  patch_len: 16
  stride: 16
  e_layers: 1
  factor: 3
  n_heads: 2
  d_ff: 2048
  d_model: 512
  dropout: 0.1
  enc_in: 7
  output_attention: False
  activation: gelu
  target_patch_size: 48
  k: 1
  loss:
    pred_loss: True
    criterion: huber

train:
  lr: 0.0001
  lradj: 'default'
  epochs: 30
  pct_start: 0.4
  patience: 5
  log_every: 1

GPU:
  use_gpu: True
  gpu: 0
  use_multi_gpu: False
  devices: '0, 1, 2, 3'